on: [push]

name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install az
        run: |
          sudo apt-get update
          sudo apt-get install curl 
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Get az version
        run: az --version
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS_AZUREWORKSHOP }}'